return {
	smw_secret_exit = function(cutscene, event)
		cutscene:text("* (It's a hole-looking hole.)")
		cutscene:text("* (For some reason,[wait:2] you feel like you can shove up an item in there.)")
		cutscene:text("* (Put the Blue Key in the hole?\n[color:red]You might not be able to come back for a while.[color:reset])")
		if cutscene:choicer({"Yes", "No"}) == 1 then
			local YOU = cutscene:getCharacter("YOU")
			local susie = cutscene:getCharacter("susie")

			cutscene:detachFollowers()

			Assets.playSound("item")
			Game.world.music:fade(0, 0.1)
			Game.world.map.ina:remove()

			local wait1, wait2 = cutscene:walkTo(YOU, 670, 665, 1, "up"), cutscene:walkTo(susie, 730, 665, 1, "up")
			cutscene:wait(function()
				return wait1() and wait2()
			end)
			cutscene:wait(0.5)

			cutscene:showNametag("Susie")
			cutscene:text("* Did you just put the key in this hole?", "nervous_side", "susie")
			cutscene:text("* What was even the point of that?", "nervous_side", "susie")
			cutscene:hideNametag()

			local keyhole = Sprite("world/keyhole", event.x+event.width/2, (event.y+event.height))
			keyhole:setOrigin(0.5, 1)
			keyhole:setScaleOrigin(0.5, 1)
			keyhole:setScale(0)
			keyhole:setLayer(YOU.layer - 0.1)
			Game.world:addChild(keyhole)

			--[[local outline = Sprite("world/keyhole_outline", 0, 0)
			--outline:setOrigin(0.5, 1)
			--outline:setScaleOrigin(0.5, 1)
			outline:setLayer(keyhole.layer + 0.1)
			keyhole:addChild(outline)]]

			Assets.playSound("keyhole")

			YOU:setFacing("down")
			susie:setFacing("right")
			susie:setSprite("shock")

			local transition_done = false
			Game.world.timer:tween(1, keyhole, {scale_x = 2, scale_y = 2}, nil, function()
				Game.world.timer:tween(0.35, YOU, {y = 640})
				Game.world.timer:tween(0.35, susie, {y = 640})

				Game.world.timer:after(0.25, function()
					local mask = MaskFX(keyhole)
					YOU:addFX(mask)
					susie:addFX(mask)
					Game.world.timer:tween(1, keyhole, {scale_x = 0, scale_y = 0}, nil, function()
						transition_done = true
					end)
				end)
			end)

			cutscene:wait(function()
				return transition_done
			end)

			cutscene:wait(cutscene:fadeOut())
			cutscene:wait(2)
			cutscene:wait(cutscene:loadMap("SFB/houses", "c_spawn"))
			cutscene:gotoCutscene("falling_skies.enter_game")
		else
			Assets.playSound("squeak")
		end
	end,
	enter_game = function(cutscene)
		local YOU = cutscene:getCharacter("SFB/YOU")
		local susie = cutscene:getCharacter("SFB/susie")
		cutscene:detachFollowers()
		cutscene:detachCamera()
		YOU.x = YOU.x - 50
		susie.x = susie.x + 50
		susie.y = YOU.y

		cutscene:setSpeaker("susie")
		cutscene:showNametag("Susie")
		cutscene:text("* What the HELL is going on?!")
		cutscene:text("* YOU??[wait:5] Can you hear me??")
		cutscene:hideNametag()
		Assets.playSound("frog")
		cutscene:wait(1)
		cutscene:showNametag("Susie")
		cutscene:text("* ...[wait:2]Okay,[wait:2] I'll take that as a yes.")
		cutscene:text("* Now can someone please turn on the-")
		cutscene:hideNametag()
		local rect = Rectangle(0, 0, SCREEN_WIDTH*2, SCREEN_HEIGHT*2)
		rect:setColor(1, 1, 1, 0)
		rect:setLayer(WORLD_LAYERS["top"])
		Game.world:addChild(rect)
		Game.world.timer:tween(1, rect, {alpha=1})
		cutscene:wait(1.5)
		cutscene:fadeIn(0)
		Game.world.timer:tween(3, rect, {alpha=0})
		cutscene:wait(3.5)
		cutscene:showNametag("Susie")
		cutscene:text("* Lights..?", "surprise")
		cutscene:hideNametag()
		cutscene:look(susie, "right")
		cutscene:wait(0.5)
		cutscene:look(susie, "left")
		cutscene:wait(0.5)
		cutscene:look(susie, "up")
		cutscene:wait(0.5)
		cutscene:look(susie, "down")
		cutscene:wait(0.5)
		cutscene:look(susie, "left")
		cutscene:wait(0.5)
		cutscene:look(susie, "right")
		cutscene:wait(0.5)
		cutscene:look(susie, "up")
		cutscene:showNametag("Susie")
		cutscene:text("* I guess the lights were already on, huh...", "smirk")
		cutscene:text("* Wait...", "sus_nervous")
		cutscene:hideNametag()
		cutscene:wait(1)
		cutscene:wait(cutscene:walkTo(susie, YOU.x+(YOU.width+20), susie.y, 0.1))
		cutscene:look(YOU, "right")
		Assets.playSound("whip")
		cutscene:showNametag("Susie")
		cutscene:text("* YOU WHERE THE HELL ARE WE???", "teeth_b")
		cutscene:text("* We were in that other version of Castle Town a minute ago!", "teeth_b")
		cutscene:text("* Then you put the key in that hole and...", "teeth_b")
		cutscene:text("* And now we're here..", "neutral")
		cutscene:hideNametag()
		cutscene:look(YOU, "down")
		cutscene:wait(cutscene:walkTo(susie, susie.x, susie.y+50))
		cutscene:wait(0.5)
		cutscene:showNametag("Susie")
		cutscene:text("* ...", "neutral")
		cutscene:look(susie, "up")
		cutscene:text("* Man, what the hell kinda thing that jester sold you?", "annoyed")
		cutscene:text("* It doesn't even look like it's our world anymore.", "annoyed")
		cutscene:text("* That's a first.", "nervous")
		cutscene:hideNametag()
		cutscene:wait(1)
		cutscene:showNametag("Susie")
		cutscene:text("* Well you know what?", "smirk")
		cutscene:text("* We won't get anywhere if we don't move right?", "smirk")
		cutscene:text("* Plus that shopkeeper did told you about someone to save, right?", "small_smile")
		cutscene:text("* So our goal here's pretty clear.", "closed_grin")
		cutscene:hideNametag()
		cutscene:wait(cutscene:attachFollowers(1))
		cutscene:look(YOU, "right")
		cutscene:look(susie, "left")
		cutscene:showNametag("Susie")
		cutscene:text("* Let's go, YOU!", "smile")
		cutscene:hideNametag()
		cutscene:interpolateFollowers()
		cutscene:wait(cutscene:attachCamera())
		cutscene:look(YOU, "down")
	end
}